[tool.poetry]
name = "orgroam-to-obsidian"
version = "0.1.0"
description = ""
authors = ["Toni Cebrián <toni@tonicebrian.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
